/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Algorithm.Chromosome;
import Algorithm.City;
import Algorithm.GeneticAlgorithm;
import Algorithm.Parameter;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.geom.*;
import java.awt.geom.Point2D;
import java.util.ArrayList;

import static Algorithm.Parameter.*;
import static Algorithm.Parameter.Cities;

/**
 *
 * @author SAKURA
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new DrawPanel();
        jPanel2 = new JPanel();
        jButtonRandomGenerate = new JButton();
        jComboBoxCityNum = new javax.swing.JComboBox<>();
        jButtonCalculate = new JButton();
        jButtonReset = new JButton();
        jLabelTheShortestLength = new JLabel();
        jLabelTheLength = new JLabel();
        jLabelTheBestPath = new JLabel();
        jLabelThePath = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 210));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1.setBackground(Color.white);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        

        jComboBoxCityNum.setEditable(true);
        jComboBoxCityNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "40", "20", "30","50" }));
        jComboBoxCityNum.setMinimumSize(new java.awt.Dimension(130, 25));
        jComboBoxCityNum.setPreferredSize(new java.awt.Dimension(130, 25));
        jComboBoxCityNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCityNumActionPerformed(evt);
            }
        });

        jButtonRandomGenerate.setText("随机生成");
        jButtonRandomGenerate.setMaximumSize(new java.awt.Dimension(130, 25));
        jButtonRandomGenerate.setMinimumSize(new java.awt.Dimension(130, 25));
        jButtonRandomGenerate.setPreferredSize(new java.awt.Dimension(130, 25));
        jButtonRandomGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomGenerateActionPerformed(evt);
            }
        });
        
        jButtonCalculate.setText("计算最佳路径");
        jButtonCalculate.setMaximumSize(new java.awt.Dimension(130, 25));
        jButtonCalculate.setMinimumSize(new java.awt.Dimension(130, 25));
        jButtonCalculate.setPreferredSize(new java.awt.Dimension(130, 25));
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });

        jButtonReset.setText("重置");
        jButtonReset.setMaximumSize(new java.awt.Dimension(130, 25));
        jButtonReset.setMinimumSize(new java.awt.Dimension(130, 25));
        jButtonReset.setPreferredSize(new java.awt.Dimension(130, 25));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jLabelTheShortestLength.setText("最佳长度:");
        jLabelTheLength.setMaximumSize(new java.awt.Dimension(400, 15));
        jLabelTheLength.setMinimumSize(new java.awt.Dimension(400, 15));
        jLabelTheLength.setPreferredSize(new java.awt.Dimension(400, 15));
        

        jLabelTheBestPath.setText("建议选取20个以上的点");
        jLabelThePath.setText("");
        jLabelThePath.setMaximumSize(new java.awt.Dimension(500, 15));
        jLabelThePath.setMinimumSize(new java.awt.Dimension(500, 15));
        jLabelThePath.setPreferredSize(new java.awt.Dimension(500, 15));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonRandomGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCityNum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTheBestPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelThePath, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTheShortestLength)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTheLength, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRandomGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCityNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTheLength, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTheShortestLength, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelThePath, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTheBestPath))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        //将窗体设置在屏幕中间
        int width = 800;
        int height = 600;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize(); //得到屏幕的尺寸
        setBounds(((screenSize.width-width)/2), ((screenSize.height-height)/2),width,height);
        setResizable(false);
    }// </editor-fold>//GEN-END:initComponents


    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        Cities.add(new City(Cities.size(),evt.getX(),evt.getY()));
        System.out.println(Cities.get(Cities.size() -1));
        point2DS.add(new Point2D.Double(evt.getX(), evt.getY()));
        jPanel1.repaint();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jComboBoxCityNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCityNumActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCityNumActionPerformed

    private void jButtonResetActionPerformed(ActionEvent evt) {
        Cities.clear();
        point2DS.clear();
        line2DS.clear();
        jPanel1.repaint();
        chartData.clear();
        chartData2.clear();
        chartDataAverage.clear();
        distance = null;
    }

    private void jButtonCalculateActionPerformed(ActionEvent evt) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                paintLine();
            }
        }).start();
    }

    private Chromosome getBestRoute() {
        return GeneticAlgorithm.Route();
    }

    private void paintLine() {
        line2DS.clear();
        Chromosome route = getBestRoute();
        int i = 0;
        for (; i < Cities.size() - 1; i++) {
            line2DS.add(new Line2D.Double(point2DS.get(route.get(i)),point2DS.get(route.get(i+1))));
//            jLabelThePath.setText(jLabelThePath.getText() + route.get(i) + "->");
        }
//        jLabelThePath.setText(jLabelThePath.getText() + route.get(i) + "->" + route.get(0));
        line2DS.add(new Line2D.Double(point2DS.get(route.get(i)),point2DS.get(route.get(0))));
        jPanel1.repaint();
        jLabelTheLength.setText((MaxDistance - route.getFitness())+"");
    }

    private void jButtonRandomGenerateActionPerformed(ActionEvent evt) {
        isNum();
        RandomGenerate();
    }

    private void RandomGenerate() {
        Cities.clear();
        point2DS.clear();
        line2DS.clear();
        double MaxWidth = jPanel1.getWidth();
        double MaxHeight = jPanel1.getHeight();
        for (int i = 0; i < cityNum; i++) {
            px = Math.random()*(MaxWidth - 1);
            py = Math.random()*(MaxHeight - 1);
            Cities.add(new City(Cities.size(),px,py));
            point2DS.add(new Point2D.Double(px, py));
        }
        jPanel1.repaint();
    }

    //判断框内是否是数字
    private void isNum() {
        String num;
        if (!((num = jComboBoxCityNum.getSelectedItem().toString()).matches("^[0-9]*[1-9][0-9]*$"))) {
            JOptionPane.showMessageDialog(null, "请输入100一下的的正整数", "警告", JOptionPane.ERROR_MESSAGE);
            jComboBoxCityNum.requestFocusInWindow();//输入不通过时焦点落回错误文本框
        } else {
            cityNum = Integer.parseInt(num);
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonCalculate;
    private JButton jButtonRandomGenerate;
    private JButton jButtonReset;
    private JComboBox<String> jComboBoxCityNum;
    private JLabel jLabelTheBestPath;
    private JLabel jLabelTheLength;
    private JLabel jLabelThePath;
    private JLabel jLabelTheShortestLength;
    private JPanel jPanel1;
    private JPanel jPanel2;


    private int cityNum = 0;
    private double px = 0;
    private double py = 0;
    private double radius = 5;
    private ArrayList<Point2D> point2DS = new ArrayList<Point2D>();
    private ArrayList<Line2D> line2DS = new ArrayList<Line2D>();

    private class DrawPanel extends JPanel {
        public void paintComponent(Graphics graphics) {
            super.paintComponent(graphics);
            Graphics2D graphics2D = (Graphics2D)graphics;
            graphics2D.setColor(Color.GREEN);
            for (Point2D point2D: point2DS
                 ) {
                graphics2D.fill(new Ellipse2D.Double(point2D.getX() - radius,point2D.getY() - radius,radius , radius));
                graphics2D.setColor(Color.RED);
            }
            graphics2D.setColor(Color.orange);
            for (Line2D line2D: line2DS
                 ) {
                graphics2D.draw(line2D);
            }
        }
    }
    // End of variables declaration//GEN-END:variables
}
